accounts/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views, api_views
from django.conf import settings

urlpatterns = [
    path('create/', views.create_account, name='register_user'),
    path('login/', views.login_view, name='login_page'),
    path('my-dashboard/', views.user_dashboard, name="dashboard"),
    path('my-address/', views.user_address, name="address"),
    path('my-order-history/', views.order_history, name="order_history"),
    path('my-support-tickets/', views.support_tickets, name="support_tickets"),
    path("activation-link/", views.activate_button, name="activation_page"),
    path("confirm-password-email/", views.confirm_pass_email, name="password_page"),
    path("activate/<uidb64>/<token>/", views.activate_account, name="activate_account"),
    path('resend/', views.resend_token, name='resend_token'),
    path('reset-password/', views.reset_password, name='reset_password'),
    path('update-password/', views.update_password, name='update_password'),
    path('change-password/<uidb64>/<token>/', views.change_password, name='change_password'),
    path('my-wishlist/', views.wishlist, name='wishlist'),
    path('my-cart/', views.cartview, name='cart'),
    path('add-to-cart/', views.add_to_cart, name="add_to_cart"),
    # path('remove-from-cart/', views.remove_from_cart, name="remove_from_cart"),
    path('add-to-wishlist/', views.add_to_wishlist, name="add_to_wishlist"),
    path('remove-from-wishlist/', views.remove_from_wishlist, name="remove_from_wishlist"),
    path('checkout/', views.checkout, name="checkout"),
    path('logout/', views.logout_user, name='logout'),
    # path('create_vendor', views.create_vendor, name='create_vendor')
]

# I added a slash to both url mappings that end with <token>. Putting this here incase the code breaks

blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.blog_home, name="blog-home")
]

shoppa/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
import accounts.views as accounts_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('help/', views.help_page, name='help'),
    path('privacy-policy/', views.privacy_policy, name='privacy_policy'),
    path('return-policy/', views.return_policy, name='return_policy'),
    path('shipping-policy/', views.shipping_policy, name='shipping_policy'),
    path('payment-policy/', views.payment_policy, name='payment_policy'),
    path('terms-and-conditions/', views.terms_and_conditions, name='terms_and_conditions'),
    path('contact/', views.help_page, name='contact'),
    path('shop/', include('products.urls')),
    path('blog/', include('blog.urls')),
    # path('api/v1/', include('products.api.api_urls')),
    path('account/', include('accounts.urls')),
    path('login/', accounts_views.login_view, name="login_account"),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:  # new
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import BaseUserManager, AbstractUser, PermissionsMixin
from django.conf import settings
from colorfield.fields import ColorField
from django.core.validators import RegexValidator
import secrets, string, random

from products.models import Product

ORDER_STATUS_CHOICES = [
    ("Delivered", "Completed"),
    ("In Progress", "In Progress"),
    ("Delayed", "Delayed"),
    ("Cancelled", "Cancelled")
]

TICKET_TYPE_CHOICES = [
    ("Website Issues", "Website Issues"),
    ("Complaint", "Complaint"),
    ("Inquiry", "Inquiry"),
    ("Order Issues", "Order Issues"),
]

TICKET_PRIORITY_CHOICES = [
    ("Low", "Low"),
    ("Medium", "Medium"),
    ("High", "High"),
    ("Urgent", "Urgent"),
]

TICKET_STATUS_CHOICES = [
    ("Open", "Open"),
    ("Closed", "Closed")
]

def alpha_numeric(length):
    order_num = ''.join(secrets.choice(string.ascii_uppercase + string.digits) for x in range(length))
    return order_num

# Remember to remove the blank=true from important model fields before you go live

# Create your models here.
class Cart(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, primary_key=True)
    cart_products = models.ManyToManyField("products.Product", blank=True, through='CartDetails')
    date_created = models.DateTimeField(default=timezone.now)

    class Meta:
        verbose_name = 'Cart'
        verbose_name_plural = 'Carts'

    def __str__(self):
        return self.user.first_name + "'s Cart"

    def get_item_count(self):
        return self.cart_products.all().count()

    def get_subtotal(self):
        for product in self.cart_products:
            # print(help(product))
            break

class CartDetails(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey("products.Product", on_delete=models.CASCADE, blank=True)
    quantity = models.IntegerField(blank=True)
    color = ColorField(default="#ffffff", blank=True)
    
    def __str__(self):
        return self.cart.user.first_name + "'s Cart"

    def total(self):
        return self.product.price * self.quantity

class Wishlist(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, primary_key=True)
    wish_products = models.ManyToManyField(Product, blank=True)
    date_created = models.DateTimeField(default=timezone.now)

    class Meta:
        verbose_name = 'Wishlist'
        verbose_name_plural = 'Wishlists'

    def get_item_count(self):
        return self.wish_products.all().count()

    def __str__(self):
        return self.user.first_name + "'s Wishlist"

class CustomAccountManager(BaseUserManager):
    def create_user(self, email, first_name, last_name, password, phone_number, **extra_fields):
        if not email:
            return ValueError('You must provide an email address')

        email = self.normalize_email(email)
        user = self.model(email=email, first_name=first_name, last_name=last_name, phone_number=phone_number, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, first_name, last_name, email, password, phone_number, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)
        extra_fields.setdefault('is_apiuser', True)
        extra_fields.setdefault('is_vendor', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(('Superuser must have is_superuser=True.'))
        if extra_fields.get('is_apiuser') is not True:
            raise ValueError(('Superuser must have is_apiuser=True.'))
        if extra_fields.get('is_vendor') is not True:
            raise ValueError(('Superuser must have is_vendor=True.'))

        return self.create_user(first_name=first_name, last_name=last_name, email=email, password=password, phone_number=phone_number, **extra_fields)
    
phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")

# class PhoneBook(models.Model):
#     phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
#     phone_numbers = models.CharField(validators=[phone_regex], max_length=17, blank=True)

# class AddressBook(models.Model):
#     address = models.CharField(max_length=250)

class CustomAccount(AbstractUser, PermissionsMixin):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField(unique=True)
    username = None
    # username = models.CharField(max_length=70, null=True, blank=True)
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True)
    # phone_number = models.ForeignKey(PhoneBook, on_delete=models.CASCADE, blank=True)
    date_joined = models.DateTimeField(default=timezone.now)
    # address = models.CharField(max_length=250, blank=True)

    is_active = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_apiuser = models.BooleanField(default=False)
    is_vendor = models.BooleanField(default=False)

    def get_full_name(self):
        return "%s %s"%(self.first_name, self.last_name)

    def get_short_name(self):
        return self.first_name

    def __str__(self):
        return self.email

    objects = CustomAccountManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['phone_number', 'first_name', 'last_name']

class ApiUser(models.Model):
    user = models.OneToOneField(CustomAccount, on_delete=models.CASCADE)
    product_groups = models.JSONField()

    def save(self, *args, **kwargs):
        if self.user.is_apiuser != True:
            raise ValueError
        super(ApiUser, self).save(*args, **kwargs)

class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, primary_key=True)
    state = models.CharField(max_length=100, blank=True)
    city = models.CharField(max_length=200, blank=True)
    street = models.CharField(max_length=300, blank=True)
    postcode = models.IntegerField(blank=True, default=000000)

    def is_completed(self):
        if (self.state == "" or self.state == " ") and (self.city == "" or self.city == " ") and (self.street == "" or self.street == " "):
            return False
        else:
            return True

class UserOrders(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, primary_key=True)
    total = models.IntegerField()
    date_purchased = models.DateTimeField(default=timezone.now)
    order_number = models.CharField(max_length=12, unique=True)# Generate an alphanumeric value here
    status = models.CharField(max_length=100, choices=ORDER_STATUS_CHOICES)

    def save(self, *args, **kwargs):
        order_number = self.order_number
        if len(order_number) != 12 and type(order_number) != str:
            alpha_num = alpha_numeric(12)
            self.order_number = str(alpha_num)
        super(UserOrders, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.user.first_name}'s Orders"

class UserTickets(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, primary_key=True)
    subject = models.CharField(max_length = 250)
    date_submitted = models.DateTimeField(default=timezone.now)
    ticket_type = models.CharField(max_length=100, choices=TICKET_TYPE_CHOICES)
    priority = models.CharField(max_length=100, choices=TICKET_PRIORITY_CHOICES)
    status = models.CharField(max_length=100, choices=TICKET_STATUS_CHOICES)

    def __str__(self):
        return f"{self.user.first_name}'s Tickets"

accounts/forms.py
from django import forms
from django.utils import timezone
from .models import CustomAccount

class LoginForm(forms.Form):
    email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder': 'Email'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))

class CreateAccountForm(forms.ModelForm):
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={"id": "second-password", "placeholder": "Confirm Password"}))

    class Meta:
        model = CustomAccount
        fields = ['first_name', 'last_name', 'email', 'phone_number', 'password']

    def __init__(self, *args, **kwargs):
        super(CreateAccountForm, self).__init__(*args, **kwargs)
        self.fields['email'].widget = forms.TextInput(attrs={'id':'register_email', 'placeholder':'Email', 'type': 'email'})
        self.fields['password'].widget = forms.TextInput(attrs={'id':'register_pass', 'placeholder':'Password', 'type': 'password'})
        self.fields['first_name'].widget = forms.TextInput(attrs={'placeholder':'First Name', 'type': 'text'})
        self.fields['last_name'].widget = forms.TextInput(attrs={'placeholder':'Last Name', 'type': 'text'})
        self.fields['phone_number'].widget = forms.TextInput(attrs={'placeholder':'Phone Number', 'type': 'tel'})
        # for visible in self.visible_fields():
        #     visible.field.widget.attrs['class'] = 'form-control border-0 mb-3'

class CheckoutForm(forms.Form):
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    state = forms.ChoiceField()
    street_address = forms.CharField(max_length=300)
    city = forms.CharField(max_length=200)
    postcode = forms.IntegerField()
    email = forms.EmailField()
    phone = forms.IntegerField()

accounts/templates/accounts/activation.html
{% extends 'base.html' %}

{% block page-title %}Activate Account Email{% endblock page-title %}

{% block main-content %}
<div class="activate-page">
    {% comment %} <p class="angry-text">We are unable to send verification emails to you because there is no email service provider that supports the community :frown :flat {% endcomment %}
        <br><br>
        <h5 class="text-center">{{ user.first_name }}, activate your account now</h5>
        <p class="my-4">To be able to login and sync your cart, click the button below to activate your account. The activation link expires after 1 hour</p>

        <a class="mx-auto" href="http://{{ domain }}{% url 'activate_account' uidb64=uid token=token %}"><button class="btn btn-style1">Activate Account</button></a>
    </div>
    {% comment %} http://{{ domain }}{% url 'activate_account' uidb64=uid token=token %} {% endcomment %}
{% endblock main-content %}

{% block custom-js %}
    <script>
        $(document).ready(function() {
            notyf.open({
                type: "info",
                message: "This is a demo of how the activation email will look",
                duration: 15000,
            });
        });
    </script>
{% endblock custom-js %}

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block main-content %}
    <div class="change-pass-page">
        <div class="change-pass-outer" id="nav-log-in">
        <h4 class="fs-34 text-center mb-2">Change Your Password</h4>
        <p class="text-secondary text-center mb-4">Submit the new password</p>
        <p class="text-center fs-16 mb-4">Don’t have an account yet? <a href="{% url 'register_user' %}" class="text-secondary border-bottom text-decoration-none">Sign up</a> for free</p>
        <form name="change-pass" method="POST" id="change-pass-form">
            {% csrf_token %}
            <input id="change-pass1" name="new_pass1" type="password" class="mb-3" placeholder="New Password" required>
            <input id="change-pass2" name="new_pass2" type="password" class="mb-4" placeholder="Confirm Your Password" required>
            <button type="submit" value="Change My Password" class="btn-style1">Change My Password</button>
        </form>
        {% comment %} sds@mail.com {% endcomment %}
    </div>
{% comment %} <script>
    $("#change-pass-form").submit(function (e) {
        e.preventDefault();
        var serializedData = $(this).serialize();
        var pass1 = $("#change-pass1").val()
        var pass2 = $("#change-pass2").val()
        $.ajax({
            type: 'POST',
            url: "{% url 'update_password' %}",
            headers: {'X-CSRFToken': csrftoken},
            mode: 'same-origin',
            data: {
                "new_pass1": pass1,
                "new_pass2": pass2,
                "uid": "{{user_id}}"
            },
            success: function (response) {
                let message;
                let alert_type;
                if (typeof(response['responseJSON']) == 'undefined') {
                    message = response['message'];
                    alert_type = response['type'];
                } else {
                    message = response['responseJSON']['message'];
                    alert_type = response['responseJSON']['type'];
                }
                if (typeof(message) == 'undefined') {
                    message = 'An Error Occurred. Please Try Again'
                    alert_type = 'error'
                    console.log(response)
                    // location.reload()
                }
                if (typeof(message) == 'object') {
                    for (const error in message) {
                        error_message = message[error]
                        notyf.open({
                            type: alert_type,
                            message: error_message,
                            duration: 7000,
                        });
                    }
                } else if (alert_type === 'success') {
                    $("#change-pass-form").trigger('reset');
                    $("#change-pass-email").focus();
                    notyf.open({
                        type: alert_type,
                        message: message,
                        duration: 7000,
                    });
                } else {
                    notyf.open({
                        type: alert_type,
                        message: message,
                        duration: 7000,
                    });
                }
            },
            error: function (response) {
                processResponse(response)
            }
        })
    })
</script> {% endcomment %}
</div>
{% endblock main-content %}

accounts/templates/accounts/chosen-cart.html
{% extends 'base.html' %}
{% load static %}

{% block page-title %}{{ request.user.first_name }}'s Cart{% endblock page-title %}

{% block imports %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/chosen-cart.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/cart-responsive.css' %}">
{% endblock imports %}

{% block main-content %}
    <!-- breadcrumb start -->
    <section class="breadcrumb-area">
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="breadcrumb-start">
                        <ul class="breadcrumb-url">
                            <li class="breadcrumb-url-li">
                                <a href="index5.html">Home</a>
                            </li>
                            <li class="breadcrumb-url-li">
                                <a href="#"><span>Cart</span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- breadcrumb end -->
    <!-- cart start -->
    <section class="cart-page section-tb-padding">
        <div class="container">
            <div class="row">
                {% if cart_item_count == 0 %}
                    <h5 class="text-center">You haven't added any items to your cart</h5>
                {% endif %}
                <div class="col-xl-9 col-xs-12 col-sm-12 col-md-12 col-lg-8 all-cart-items">
                    {% if cart_item_count != 0 %}
                        <div class="cart-item">
                            <span class="cart-head">My Cart:</span>
                            <span class="c-items">{{ cart_item_count }} item{% if cart_item_count > 1 %}s{% endif %}</span>
                        </div>
                    {% endif %}
                    {% if request.user.is_authenticated %}
                        {% for item in user_cart.cartdetails_set.all %}
                            {% with item.product as product and item.quantity as quantity %}
                                <div class="cart-area">
                                    <div class="cart-details">
                                        <div class="cart-all-pro">
                                            <div class="cart-pro">
                                                <div class="cart-pro-image">
                                                    <a href="{{ product.get_absolute_url }}"><img src="{{ product.image.url }}" class="img-fluid" alt="image"></a>
                                                </div>
                                                <div class="pro-details">
                                                    <h4 class=""><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></h4>
                                                    <div class="rating mt-2">
                                                        <i class="fa fa-star c-star"></i>
                                                        <i class="fa fa-star c-star"></i>
                                                        <i class="fa fa-star c-star"></i>
                                                        <i class="fa fa-star-o"></i>
                                                        <i class="fa fa-star-o"></i>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="qty-item">
                                                <form method="post" class="center">
                                                    {% csrf_token %}
                                                    <div class="plus-minus">
                                                        <span>
                                                            <a href="javascript:void(0)" class="minus-btn text-black">-</a>
                                                            <input type="text" name="name" value="{{ quantity }}">
                                                            <a href="javascript:void(0)" class="plus-btn text-black">+</a>
                                                        </span>
                                                    </div>
                                                    <button name="remove_from_cart" value="{{ product.id }}" class="btn-style3 del-btn">Remove</button>
                                                    <button name="remove_from_cart" value="{{ product.id }}" class="del-icon"><span class="material-symbols-outlined">delete</span></button>
                                                </form>
                                            </div>
                                            <div class="all-pro-price">
                                                <span>₦{{ item.total }} NGN</span>
                                                <span class="old-price">₦{{ product.price }} NGN</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endwith %}
                        {% endfor %}
                    {% else %}
                        {% for item in user_cart.items %}
                            {% with item.product as product and item.quantity as quantity %}
                                <div class="cart-area">
                                    <div class="cart-details">
                                        <div class="cart-all-pro">
                                            <div class="cart-pro">
                                                <div class="cart-pro-image">
                                                    <a href="{{ product.get_absolute_url }}"><img src="{{ product.image.url }}" class="img-fluid" alt="image"></a>
                                                </div>
                                                <div class="pro-details">
                                                    <h4 class=""><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></h4>
                                                    <div class="rating mt-2">
                                                        <i class="fa fa-star c-star"></i>
                                                        <i class="fa fa-star c-star"></i>
                                                        <i class="fa fa-star c-star"></i>
                                                        <i class="fa fa-star-o"></i>
                                                        <i class="fa fa-star-o"></i>
                                                    </div>
                                                </div>
                                            </div>
                                            <form class="qty-item" method="post">
                                                {% csrf_token %}
                                                <div class="center">
                                                    <div class="plus-minus">
                                                        <span>
                                                            <a href="javascript:void(0)" class="minus-btn text-black">-</a>
                                                            <input type="text" name="name" value="{{ quantity }}">
                                                            <a href="javascript:void(0)" class="plus-btn text-black">+</a>
                                                        </span>
                                                    </div>
                                                    <button name="remove_from_cart" value="{{ product.id }}" class="btn-style3 del-btn">Remove</button>
                                                    <button name="remove_from_cart" value="{{ product.id }}" class="del-icon"><span class="material-symbols-outlined">delete</span></button>
                                                </div>
                                            </form>
                                            <div class="all-pro-price">
                                                <span>₦{{ item.total }} NGN</span>
                                                <span class="old-price">₦{{ product.price }} NGN</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endwith %}
                        {% endfor %}
                    {% endif %}
                    {% if cart_item_count != 0 %}
                        <form class="other-link" method="post">
                            {% csrf_token %}
                            <ul class="c-link">
                                <li class=""><a class="btn-style1" href="grid-list.html">Update cart</a></li>
                                <li class=""><a class="btn-style1" href="grid-list.html">Continue shopping</a></li>
                                <li class=""><button class="btn-style1" name="clear_cart" value="True">Clear cart</button></li>
                            </ul>
                        </form>
                    {% endif %}

                </div>
                {% if cart_item_count > 0 %}
                    <div class="col-xl-3 col-xs-12 col-sm-12 col-md-12 col-lg-4 shipping-total">
                        <div class="cart-total">
                            <div class="cart-price">
                                <span>Subtotal</span>
                                <span class="total">₦{{ subtotal }} NGN</span>
                            </div>
                            <div class="cart-price">
                                <span>Shipping and Delivery</span>
                                <span class="total">₦8.90 NGN</span>
                            </div>
                            <div class="cart-info">
                                <h4>Shipping info</h4>
                                <form>
                                    <label>Country</label>
                                    <select class="form-select" aria-label="Default select example">
                                        <option>---</option>
                                        <option>Afghanistan</option>
                                        <option>Åland Islands</option>
                                        <option>Albania</option>
                                        <option>Algeria</option>
                                        <option>Andorra</option>
                                        <option>Angola</option>
                                        <option>Anguilla</option>
                                        <option>Antigua & Barbuda</option>
                                        <option>Argentina</option>
                                        <option>Armenia</option>
                                        <option>Aruba</option>
                                        <option>Ascension Island</option>
                                        <option>Australia</option>
                                        <option>Austria</option>
                                        <option>Azerbaijan</option>
                                        <option>Bahamas</option>
                                        <option>Bahrain</option>
                                    </select>
                                    <label>Zip/postal code</label>
                                    <input type="text" name="code" placeholder="Zip/postal code">
                                </form>
                                <a href="javascript:void(0)" class="btn-style3 calculate-btn">Calculate</a>
                            </div>
                            <div class="shop-total">
                                <span>Total</span>
                                <span class="total-amount">₦78.44 NGN</span>
                            </div>
                            <a href="{% url 'checkout' %}" class="btn-style1 d-block text-center mt-3 checkout">Checkout</a>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </section>
    <!-- cart end -->
{% endblock main-content %}

accounts/templates/accounts/confirm_email.html
{% comment %} {% extends 'base.html' %} {% endcomment %}
{% autoescape off %}
    Hi {{ user.last_name }},
    Please click on the link below to confirm your registration. Your confirmation link will expire in one hour.

    When your account is activated successfully,you can login.

    http://{{ domain }}{% url 'activate_account' uidb64=uid token=token %}
{% endautoescape %}

accounts/templates/accounts/reset_password_email.html
{% autoescape off %}
    Hi {{ user.last_name }},
    Please click on the link below to confirm your registration. Your confirmation link will expire in one hour.

    http://{{ domain }}{% url 'change_password' uidb64=uid token=token %}
{% endautoescape %}